openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
  description: Hello!
paths: {}
components:
  schemas:
    AwsWidget:
      allOf:
        - $ref: base.yml#/components/schemas/Widget
        - type: object
          properties:
            awsProviderId:
              type: string
            region:
              description: The AWS region to use with this widget
              type: string
            showDeepLinks:
              type: boolean
              default: false
    AwsCloudWatchMetricGraph:
      description: A widget that displays a cloudwatch graph with a number of metrics. The default graph selection may be provided. By default, each graph has a timerange, period, and statistic selector enabled.
      allOf:
        - $ref: '#/components/schemas/AwsWidget'
        - type: object
          properties:
            statistic:
              type: string
              description: A cloudwatch supported statistic, as defined here https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Statistics-definitions.html. Not all statistics are supported for all metrics
              default: Average
            showTimeRangeSelector:
              type: boolean
              default: true
            showStatisticSelector:
              type: boolean
              default: true
            showPeriodSelector:
              type: boolean
              default: true
            metrics:
              type: array
              items:
                type: object
                properties:
                  metricNamespace:
                    type: string
                  metricName:
                    type: string
                  metricDisplayName: 
                    type: string
                  dimensions:
                    type: array
                    items:
                      $ref: '#/components/schemas/KeyValuePair'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        value: number
                        unit: string
                required:
                  - metricNamespace
                  - metricName
                  - dimensions
            timeRage:
              oneOf:
                - $ref: '#/components/schemas/TimeRange'
                - $ref: '#/components/schemas/RelativeTime'
              default:
                time: 5
                unit: 'm'
          required:
            
    AwsCloudWatchLogViewer:
      description: A widget that displays CloudWatch logs for a log group or log stream. ARNs or IDs may be provided for log group and log stream ids. By default, a timerange selector is provided.
      allOf:  
        - $ref: '#/components/schemas/AwsWidget'
        - type: object
          properties:
            logGroupId:
              type: string
            logStreamId:
              type: string
            defaultTimeRange:
              oneOf:
                - $ref: '#/components/schemas/TimeRange'
                - $ref: '#/components/schemas/RelativeTime'
    AwsEcsServiceDeployments:
      description: This widget shows service deployment details.
      allOf:  
        - $ref: '#/components/schemas/AwsWidget'
        - type: object
          properties:
            clusterName:
              type: string
            serviceName:
              type: string
            showTasks:
              type: boolean
              default: true
            showTaskFilters:
              type: boolean
              default: true
            showTaskDetails:
              type: boolean
              default: false
            showPermissions:
              type: boolean
              default: false
    TimeRange:
      description: All times are UNIX datetimes
      properties:
        startTime:
          type: number
        endTime:
          type: number
    RelativeTime:
      properties:
        time:
          type: number
        unit:
          $ref: '#/components/schemas/TimeUnitEnum'
    TimeUnitEnum:
      type: string
      enum:
        - ns
        - ms
        - s
        - m
        - h
        - d
        - w
        - mo
        - yr
    KeyValuePair:
      properties:
        key:
          type: string
        value:
          type: string